### ISSUE TITLE
量信考试咨询

### ISSUE THREAD

**Issue by 73Emilie** [Chen-Jialin/Introduction-to-Quantum-Information-Assignments#1]
学长：
  你好！
  我的研究方向与量子信息毫无关系，却误打误撞选了这门课程，以为冠以导论之名课程不会太难，不想等意识到它难度的时候，该门课程已经不能退选。现期末将近，复习进程缓慢，眼看可能要挂科，见学长去年也选过这门课，想询问一下是否还记得期末考试（量子计算部分）题目的知识点。本人水平较差，只祈求能顺利通过考试即可。若学长还记得并愿意相告，感激不尽！😭

**Comment by Chen-Jialin** [comment]
同学你好，

既然你诚心诚意地求救了，那我就大发慈悲地帮助你。[这个仓库](https://github.com/Chen-Jialin/Introduction-to-Quantum-Information-Exam) 是我对 21 年秋学期量信导期末考试的试题回忆的存档，希望可以帮到你。祝考试顺利！

Best regards,
Jialin Chen
